apiVersion: v1
kind: Template
labels:
  template: jenkins-slave-python37-template
metadata:
  name: jenkins-slave-python37-template
  annotations:
    description: Jenkins slave for building python apps
    iconClass: icon-python
    tags: jenkins,python
    version: 1.0.0
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${JENKINS_SLAVE_NAME}
    name: ${JENKINS_SLAVE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${JENKINS_SLAVE_NAME}:v3.11
    runPolicy: Serial
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins-slave-base-centos7:v3.11
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 2
    labels:
      build: ${JENKINS_SLAVE_NAME}
    name: jenkins-slave-base-centos7
  spec:
    dockerImageRepository: docker.io/openshift/jenkins-slave-base-centos7
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    name: ${JENKINS_SLAVE_NAME}
    labels:
      role: jenkins-slave
    annotations:
      slave-label: python
  spec:
parameters:
- description: The name for the Jenkins slave.
  name: JENKINS_SLAVE_NAME
  value: jenkins-slave-python37
  required: true
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/dav1dli/openshift-python37-jenkins-slave.git
  required: true
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
  required: true
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  value: .
  required: true
